### ISSUE TITLE
FirePlace Capability

### ISSUE THREAD

**Issue by iRayanKhan** [danmandle/bond#2]
Hello, Bond has added the FirePlace capability, will this api be updated to include it? Thanks!

**Comment by danmandle** [comment]
Unfortunately I don't have a fireplace to test with. If you do, let me know and we can take a look and at what the API returns.

**Comment by iRayanKhan** [comment]
I have a fire place, but not a remote one, in fact I had no idea Fireplaces could work with remotes 'till I got my bond. I was just asking since for a project Homebridge-bond to make bond work with HomeKit a user asked for FirePlace capability.

**Comment by iRayanKhan** [comment]
Closed; Fire Places are only for a small number of people to use especially with the project I am working on currently.
